baseurl = "/"
languageCode = "en-us"
title = "G Georges"

[params]
  description = "An example website for G George's using [Victor Hugo](https://github.com/netlify/victor-hugo)."

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 2
[[menu.main]]
    name = "Drinks"
    url  = "/drinks"
    weight = 3
